"""initial script

Revision ID: 4c4c2d89da85
Revises:
Create Date: 2026-09-05 10:27:05.609619

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4c4c2d89da85"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
