"""add profile pics to users

Revision ID: b0b6977e85a1
Revises: da0fb1085793
Create Date: 2026-09-24 21:10:19.647468

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0b6977e85a1"
down_revision: str | Sequence[str] | None = "da0fb1085793"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("profile_image", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image")
    # ### end Alembic commands ###
