"""initial migration

Revision ID: cb982a899053
Revises: d7da879b47aa
Create Date: 2026-09-05 21:53:47.588374

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb982a899053"
down_revision: str | Sequence[str] | None = "d7da879b47aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_collections_cover_image_id",
        "collections",
        "media",
        ["cover_image_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_collections_cover_image_id", "collections", type_="foreignkey"
    )
    # ### end Alembic commands ###
